### PR TITLE
Move viewport config to addon folder close #124

### LINKED ISSUE #124: Error: Could not find module `@ember/polyfills` imported from `myapp/initializers/viewport-config`
I get the error in the browser console as soon as the server runs. 
I am using: 
`ember-in-viewport: ^2.1.1`
`ember-cli: ^2.12.3`

I've cleaned node and bower modules a couple of times, but the issue remains. Any ideas?

### PR DESCRIPTION
**Pull request by snewcomer**
Users not yet migrated to the new ember imports will see a failure with our initializer.  If moved to the addon folder and re-exported, this error can be fixed.

close #124

### CODE REVIEW

File: addon/initializers/viewport-config.js [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+if (canUseDOM) {
+  defaultConfig.viewportListeners.push({
+    context: document,
+    event: 'touchmove.scrollable'
+  });
+}
+
+export function initialize() {
+  const application = arguments[1] || arguments[0];
+  const config = application.resolveRegistration('config:environment');
```
Comment (snewcomer) [inline addon/initializers/viewport-config.js]: THis part is the only difference after migrating.  Get the config from `resolveRegistration`
